### ISSUE TITLE
What is mean the labelset

### ISSUE THREAD

**Issue by wkshare** [automixer/gobi#4]
The project is so cool!

```
  # Supported flows aggregation labels (default: SamplerAddress)
  labelset: ["Type", "FlowDirection", "SamplerAddress", "SrcAddr", 
             "DstAddr", "Etype", "Proto", "SrcPort", "DstPort", 
             "InIf", "OutIf", "SrcAS", "DstAS", "NextHop", "NextHopAS", 
             "SrcNet", "DstNet", "SrcCountry", "DstCountry"]
```

My flow record:
```
Flow Record:
  Flags        =              0x06 NETFLOW v9, Unsampled
  label        =            <none>
  export sysid =                 1
  size         =                68
  first        =        1681290659 [2023-04-12 17:10:59]
  last         =        1681290719 [2023-04-12 17:11:59]
  msec_first   =               168
  msec_last    =               896
  src addr     =     192.168.122.1
  dst addr     =    192.168.122.26
  src port     =               161
  dst port     =               161
  fwd status   =                 0
  tcp flags    =              0x00 ........
  proto        =                17 UDP
  (src)tos     =                 0
  (in)packets  =               501
  (in)bytes    =             81420
  input        =                 1
  output       =                 0
  src as       =                 0
  dst as       =                 0
```

How to mapping them?

I should config "labelset" as below?
 labelset: ["src as", "dst as", "src port", "dst port", ... ...]

Please help :)

**Comment by automixer** [comment]
Hi,
You can use "labelset" as an "aggregation keys list" of the fields included in the flow record.  So, for example, the labelset ```labelset: ["SamplerAddress", "SrcAddr", "DstAddr", "DstPort"]``` would produce a Prometheus series for each combination of these fields if feeded with a stream of flow records like the previous one.

Of course, gobi can only aggregate fields available in the flow record. In this example, your flow record does not contain source and destination AS (are both 0) and hence we cannot use the ``` "SrcAS", "DstAS"``` aggregators.

As a general gobi deployment rule, you can follow this:
1) Decide the fields you're interested in (source and dest addresses, source and dest net mask, etc..).
2) Configure the flow exporter on your device accordingly, so that these fields are correctly exported.
3) Configure the gobi labelset to aggregate all these information in a way that makes sense for you.

**Comment by wkshare** [comment]
Thank you @automixer 
I'll try again.
