### ISSUE TITLE
How to debug gobi?

### ISSUE THREAD

**Issue by wkshare** [automixer/gobi#5]
I've encountered some errors but don't know how to debug Gobi, can you provide any advice?

  | Last | Min | Max | Mean
-- | -- | -- | -- | --
Untracked traffic | 20.5 b/s | 0 b/s | 107 kb/s | 29.4 kb/s
error_decoding | 26.9 kHz | 15.8 kHz | 27.1 kHz | 25.3 kHz
-- | -- | -- | -- | --
template_not_found | 0 Hz | 0 Hz | 0.0833 Hz | 0.0224 Hz

**Comment by wkshare** [comment]
Hi @automixer 

I am testing Gobi, using a tool: https://github.com/mshindo/NetFlow-Generator

Do you have other tools that can test netflow data?

**Comment by automixer** [comment]
Hi @wkshare ,
I never tried  https://github.com/mshindo/NetFlow-Generator, but since GoFlow2 can accept NF5 data, it could be a useful tool for testing. My preferred way for debugging is to record an actual IPFIX stream coming from a router with tcpdump and then replay it to the GoFlow2 collector with [tcpreplay](https://github.com/appneta/tcpreplay). Another way could be using virtual routers, like the Juniper vSRX or the Cisco CSR1000v in a virtual network environment, configured to export a true NF stream to GoFlow2/gobi.

To properly debug gobi, there are two main aspects:
1) NetFlow-related issue. The ```error_decoding``` and ```template_not_found```fall into this category. The [GoFlow2](https://github.com/netsampler/goflow2) project documentation, the flow exporter user manual, and the IPFIX rfc are the best documentation sources. **The ```error_decoding``` counter in your table looks very high and probably this means that GoFlow2 is not accepting the NetFlow-Generator stream for some reason...**
2) Flow aggregation issues: The ``Untracked traffic `` counter is a gobi feature that can help keep the Prometheus cardinality under control. This is controlled by the ```minbps``` and ```minpps``` configuration keys and can be disabled by setting them to zero. I would suggest setting them to zero initially and adjusting them later if needed.

**Comment by wkshare** [comment]
@automixer  Thanks again.

I set minbps to 0. It's work fine.

This project is very great. We are considering it for production environments：）
